const JWT_SECRET = process.env.JWT_SECRET || 'nacionpay-secret-key-2024';
const JWT_EXPIRY = '30m';
const JWT_REFRESH_EXPIRY = '7d';
const MAX_INTENTOS = 5;
const VENTANA_BLOQUEO_MS = 10 * 60 * 1000;     // 10 minutos (RF-002)
const BLOQUEO_DURACION_MS = 30 * 60 * 1000;     // 30 minutos (RF-002)
const TOPE_CCE_PEN = 30000;
const TOPE_CCE_USD = 10000;
const VENTANA_ESTRUCTURACION_MS = 2 * 60 * 60 * 1000;
const UMBRAL_CONTEO_ESTRUCTURACION = 15;
const UMBRAL_MONTO_ESTRUCTURACION = 1800;
const QR_VIGENCIA_MS = 5 * 60 * 1000;           // 5 minutos (RF-007)
const MAX_RECARGA_SEGUNDOS = 60;                 // 60 segundos (RF-009)
const SESION_INACTIVIDAD_MS = 5 * 60 * 1000;    // 5 minutos (RNF-003)
const BCRYPT_ROUNDS = 12;                        // RNF-003

module.exports = {
  JWT_SECRET, JWT_EXPIRY, JWT_REFRESH_EXPIRY,
  MAX_INTENTOS, VENTANA_BLOQUEO_MS, BLOQUEO_DURACION_MS,
  TOPE_CCE_PEN, TOPE_CCE_USD,
  VENTANA_ESTRUCTURACION_MS, UMBRAL_CONTEO_ESTRUCTURACION, UMBRAL_MONTO_ESTRUCTURACION,
  QR_VIGENCIA_MS, MAX_RECARGA_SEGUNDOS, SESION_INACTIVIDAD_MS, BCRYPT_ROUNDS
};
