const JWT_SECRET = process.env.JWT_SECRET || 'nacionpay-secret-key-2024';
const JWT_EXPIRY = '30m';
const MAX_INTENTOS = 5;
const VENTANA_BLOQUEO_MS = 300000;
const TOPE_CCE_PEN = 30000;
const TOPE_CCE_USD = 10000;
const VENTANA_ESTRUCTURACION_MS = 7200000;
const UMBRAL_CONTEO_ESTRUCTURACION = 15;
const UMBRAL_MONTO_ESTRUCTURACION = 1800;

module.exports = {
  JWT_SECRET,
  JWT_EXPIRY,
  MAX_INTENTOS,
  VENTANA_BLOQUEO_MS,
  TOPE_CCE_PEN,
  TOPE_CCE_USD,
  VENTANA_ESTRUCTURACION_MS,
  UMBRAL_CONTEO_ESTRUCTURACION,
  UMBRAL_MONTO_ESTRUCTURACION
};
